# Generated by roxytest: Do not edit by hand!

context("File R/get_seurat_workflow.R: @tests")

test_that("Function get_seurat_workflow() @ L20", {
  alldata@meta.data$stim <- alldata@meta.data$donor
  alldata <- get_seurat_workflow(alldata)
  expect_equal(colnames(alldata@meta.data),colnames(newdata@meta.data))
})

