# Generated by roxytest: Do not edit by hand!

context("File R/get_querydata_preprocess.R: @tests")

test_that("Function get_query_preprocess() @ L19", {
  querydf <- get_query_preprocess(newdata,species = "human",cellgroup="celltype_match",clusterlevel = TRUE)
  expect_equal(class(query_df),"data.frame")
})

