# Generated by roxytest: Do not edit by hand!

context("File R/get_reference_setname.R: @tests")

test_that("Function get_reference_setname() @ L21", {
  organtype = "liver"
  tissuetype = "health"
  
  datasetname = get_reference_setname(organtype,tissuetype)
  expect_equal(datasetname,"ref_health_liver_cor_list")
})

